config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#accueil'
  get 'cgv', to: 'pages#cgv'
  get 'le-cabinet-magnetiseur', to: 'pages#lecabinet'
  get 'cookies', to: 'pages#cookies'
  get 'mentions-legales', to: 'pages#mentionslegales'
  get 'soins-magnetiseur-marseille', to: 'pages#soins'
  get 'vos-questions', to: 'pages#vosquestions'
  get 'magnetiseur-marseille', to: 'pages#whoiam'
  get 'deontologie', to: 'pages#deontologie'
  # get 'votre-temoignage', to: 'temoignages#votremoignage'
  # get 'temoignage', to: 'temoignages#temoignage'

  get 'temoignages', to: 'temoignages#index'
  get 'temoignages/new', to: 'temoignages#new'
  post 'temoignages', to: 'temoignages#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/temoignage.rb
class Temoignage < ApplicationRecord
  validates :prenom, :nom, length: { minimum: 3 }
  validates :email, presence: true
  validates :commentaires, length: { minimum: 130 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def whoiam; end

  def accueil; end

  def cgv; end

  def lecabinet; end

  def cookies; end

  def mentionslegales; end

  def temoignage; end

  def votremoignage; end

  def soins; end

  def vosquestions; end

  def deontologie; end
end

app/controllers/temoignages_controller.rb
class TemoignagesController < ApplicationController
  def index
    @temoignages = Temoignage.all
  end

  def new
    @temoignage = Temoignage.new
  end

  def create
    @temoignage = Temoignage.new(temoignage_params)
    @temoignage.save
    redirect_to temoignages_path(@temoignage), notice: 'Votre expérience est partagée, merci !'
  end

  private

  def temoignage_params
    params.require(:temoignage).permit(:prenom, :nom, :email, :commentaires)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/temoignages_helper.rb
module TemoignagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta http-equiv="content-language" content="fr">
    <meta http-equiv="content-type" content="text/html; charset=utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <%# <base href="https://www.soins-magnetiseur-marseille.fr/"> %>
    <meta name="rights" content="Webdesign by Christophe JULLIEN magnetiseur">
    <meta name="lang" content="fr-FR">
    <meta name="robots" content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1">
    <meta name="description" content="Thérapeute magnétiseur et énergéticien à Marseille, à Paris, à Lyon, à Bordeaux, à distance dans toute la France et dans le monde entier">
    <meta name="author" content="Jullien Christophe, magnétiseur à Marseille">
    <meta property="og:description" content="Magnétiseur et énergéticien, à Marseille, dans toute la France et le monde entier.">
    <meta property="og:title" content="Magnétiseur à Marseille">
    <meta property="og:site_name" content="Christophe Magnétiseur"/>

    <%# <link rel="canonical" href="https://www.soins-magnetiseur-marseille.fr/"> %>
    <%# <meta property="og:url" content="https://www.soins-magnetiseur-marseille.fr/"> %>
    <meta name="google" content="nositelinkssearchbox">
    <meta name="referrer" content="unsafe-url">
    <meta property="og:type" content="soin magnétiseur énergéticien marseille">
    <meta name="keywords" content="magnétiseur marseille, soin marseille, soin magnétiseur, soin énergétique, soin énergétique marseille, soin magnétiseur marseille,méthode Poyet,osthéofluidique,méthode Poyet marseille,osthéofluidique marseille, osthéopathe, osthéopathe marseille">
    <title>
      Magnétiseur à Marseille
    </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<nav class="nav">
        <div class="container">

            <div class="logo">
                <%= link_to 'Christophe, magnétiseur', magnetiseur_marseille_path %>
                <img class="logo" src="/assets/Coordonnéestél.png" alt="">
            </div>

            <div id="mainListDiv" class="main_list">
                <ul class="navlinks">
                    <li><%= link_to 'Accueil', root_path %></li>
                    <li><%= link_to 'Prestations', soins_magnetiseur_marseille_path %></li>
                    <li><%= link_to 'Le Cabinet', le_cabinet_magnetiseur_path %></li>
                </ul>
            </div>
            <span class="navTrigger">
                <i></i>
                <i></i>
                <i></i>
            </span>
        </div>
</nav>

 <%= yield %>


<div class="pied">
  <div class="footer">
    <p>Site web propulsé et conçu par <%= link_to 'Christophe JULLIEN', magnetiseur_marseille_path %></p>
  </div>
  <div class="footer-2">
      <h3><%= link_to 'Mention Légale', mentions_legales_path %> | <%# <%= link_to 'CGV', cgv_path %>  <%# <%= link_to 'Cookies', cookies_path %>
          <%= link_to 'Le cabinet', le_cabinet_magnetiseur_path %> | <%= link_to 'Témoignages', temoignages_path %>
      |   <%= link_to 'Vos questions', vos_questions_path %></h3>
  </div>
</div>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script>
        $(window).scroll(function() {
            if ($(document).scrollTop() > 50) {
                $('.nav').addClass('affix');
                console.log("OK");
            } else {
                $('.nav').removeClass('affix');
            }
        });
    </script>


    <%# <script src="js/scripts.js"></script> %>
    <%# <script src="main.js"></script> %>

  </body>
</html>

app/views/pages/accueil.html.erb
    <section class="home">
    <div></div>
     <%# <img id="HMT" src="/assets/ciel-escalier2.png" alt=""> %>
    <%# <video src="/assets/bouddha.mp4" controls autoplay loop></video> %>
      <div class=entrer>
        <h1>Entrez dans votre Lumière Intérieure Sacrée</h1>
      </div>
    </section>

    <div style="height: auto">
        <!-- just to make scrolling effect possible -->
        <br>
			<h1 class="myH2">Notre corps nous parle, écoutons-le !</h1>
      <br>
        <p class="myP">
        "Toute maladie porte en elle le germe de sa guérison ", dit <a target="_blank" href="https://souzenelle.eu/">Annick De Souzenelle</a>
        <br> <br>
        "Tout déprimé est un bien portant qui s'ignore"
          affirme le <a target="_blank" href="https://www.livredepoche.com/auteur/pr-michel-lejoyeux">Pr Lejoyeux</a> .
          <br> <br>
          Nous sommes ici dans quelque chose qui dépasse le simple intellect, la logique cartésienne et qui touche du doigt, pour
          ne pas dire saisir, l'approche thérapeutique des soins énergétiques et de magnétismes, et globalement les thérapies holistiques.
          En effet, c'est en lisant l'information-énergie non-accomplie contenue dans nos espaces intérieurs qui créée le déséquilibre
          homéostatique, que la solution s'y trouve.
          <br>
          <br> Certains traduisent "maladie" par "le mal à dit", que l'on pourrait comprendre comme :
          <br> si l'on écoute notre douleur, elle nous dira pourquoi elle est là !
          <br>
          <br> La médecine chinoise ne dit-elle pas aussi que le Yin contient le Yang (et vice versa) ?
          <br> C'est par le verbe que le non-dit, le non-accompli, la maladie, sera mis en lumière et deviendra une énergie structurante
           et nourrissante.
        </p>
        <br>

				<p class="myP">
          Installé à Marseille, je vous propose de vous apporter mon expérience et mon aide pour avancer dans votre vie.
          Les soins de magnétisme ou d'énergétique, sont des techniques douces, sans manipulation, ni 'craking' et traitent tout
          dysfonctionnement de type :
            <div class="li">
              <ul class="myP">
                <li>mécaniques</li>
                <li>physiologiques</li>
                <li>psychologiques</li>
                <li>énergétiques</li>
              </ul>
            </div>
        </p>

        <p class="myP">
           Le travail peut, selon l'axe du soin, réparer les dérèglements transgénérationnelles ou de vies passées.
           Tout se passe en douceur et dans le respect de la personne, dans sa capacité à recevoir le soin de magnétisme ou énergétique.
           Chaque personne n'a pas la même capacité à recevoie ce soin et à l'intégrer.
           Chaque blocage énergétique à un sens et donne une explication au maux, quand celle-ci apporte un sens.
           Il s'agit donc de relancer les énergies bloquées et de les repositionner à leur place.
           Chaque soin ramène un peu plus l'homéostasie énergétique des corps qui sont en demandes.
			  </p>
    </div>

app/views/pages/deontologie.html.erb
<section class="deontologie"></section>

<div class="deon">
<h1>Déontologie</h1>
<%# <p class="myP">
Une grande importance à la rigueur éthique et morale ainsi qu’au respect d’une déontologie est posée en conscience et sens dans
mon activité professionnelle de magnétiseur, par respect pour les patients qui me font confiance et aussi pour faire connaître et respecter,
 à mon niveau, cette profession mal connue et encore victime de préjugés.
<br><br>
C’est en posant une éthique franche et sincère, que le praticien éloigne de lui toute forme de flatterie qui nourrit son ego : ce n’est pas
 le magnétiseur qui guéri mais bien le consultant lui-même par l’activation de ses propres capacités vitales.
Je suis un thérapeute magnétiseur-énergéticien et je ne suis donc pas un médecin ni un professionnel de santé.
Je ne formule aucun diagnostic et je ne donne aucun conseil, ni avis, sur les traitements médicaux en cours ou à venir.
Cependant, les actions du magnétiseur interviennent en complément de la médecine conventionnelle et participent au mieux-être en renforçant
 le terrain énergétique du consultant.
</p> %>

<h2>Traitements conventionnels</h2>
<p class="myP">
Je ne suis pas médecin et je ne formule pas de diagnostic. Mes soins ne vous dispensent pas de faire les examens d’investigations nécessaires
 et de suivre le traitement médical qui vous a été prescrit par votre médecin traitant. Votre suivi médical ne peut être intérompu que par
 votre médecin traitant.
</p>

<h2>Engagements</h2>
<p class="myP">
Je m’engage, dans la limite de mes capacités, à vous accompagner dans la libération de vos difficultés et dysfonctionnements énergétiques.
Je peux être amené à refuser d’intervenir si j’estime que cela ne relève pas de mes compétences ou que cela pourrait nuire à votre intégrité.
</p>

<h2>Consentement</h2>
<p class="myP">
J’interviens uniquement sur les personnes qui en ont fait expressément la demande.
<br>
Pour les personnes mineures, j’interviens à la demande des parents ou du responsable légal, et uniquement en leur présence.
</p>

<h2>Respect du secret</h2>
<p class="myP">
J'applique le secret professionnel et vous garantis une discretion assurée lors de nos échanges.
</p>

<h2>Cadre professionnel</h2>
<p class="myP">
Je pratique à distance ou je m’engage à vous accueillir dans un cabinet de soins énergétiquement sain.
Je ne pratique pas de manipulation physique comme pourrait le faire un ostéopathe. Les séances se pratiquent totalement habillées (sans chaussures).
</p>

<h2>Autonomie</h2>
<p class="myP">
Le travail sur les champs énergétiques doit vous amener à devenir plus conscient, plus éclairé dans vos choix de vie et à vous rapprocher
de votre unification intérieure. Je vous propose un accompagnement sur le chemin qui vous conduit à devenir votre propre source de guérison
et attire votre attention sur votre responsabilité et vos efforts à poser .
</p>
</div>

app/views/pages/lecabinet.html.erb
<section class="lecabinet"></section>
<br>
<br>
<div class="coordocab">
  <div class="myP" id="cartecabinet">
    <img  src="/assets/mapCabot.png" alt="">

    <div>
      <a target="_blank" href="https://www.google.com/maps/dir//38+Bd+du+Redon,+13009+Marseille/@43.2552889,5.4192898,330m/data=!3m1!1e3!4m8!4m7!1m0!1m5!1m1!1s0x12c9b8ebe3779559:0xc7b2f3acdb150881!2m2!1d5.4198718!2d43.2551424">Votre itinéraire ici</a>
    </div>
  </div>

    <div id="coordocabinet">
      <img src="/assets/Coordonnées-cabinet.png" alt="">
    </div>
</div>

app/views/pages/mentionslegales.html.erb
<section class="mtl"></section>
<div class="mentions">
  <h1>Mentions Légales</h1>
<p class="myP">
    Le Propriétaire du Site est : <%= link_to 'Christophe JULLIEN', magnetiseur_marseille_path %>
    <br><br>Statut du propriétaire : Indépendant - Profession libérale
 <%#   <br> Adresse : 1 Rue André Isaia, bâtiment F, 13013 Marseille
    <br>Tél : 06 19 94 07 24
   <br> N° SIRET :
    <br>N° Immatriculation : %>
    </p>
    <div class="coordo">
    <img src="/assets/Coordonnées.png" alt="">
    </div>
<p class="myP">
    <br>Préfet de région : Provence-Alpes-Côte d’Azur
   <br> Numéro TVA intracommunautaire : Non soumis à la T.V.A.
</p>

<p class="myP">
  L’Hébergeur du site est : O2Switch – 2 rue Kellermann – 59100 Roubaix – France
  <br>Le responsable de la publication est une personne physique
  <br><br>L’éditeur a ouvert ce site accessible par l’adresse
  <%= link_to 'www.soins-magnetiseur-marseille.fr', root_path %>
  pour l’information personnelle de ses utilisateurs.
</p>

  <h2>Editeur</h2>
    <p class="myP">Vous êtes actuellement connecté au site internet de <%= link_to 'www.soins-magnetiseur-marseille.fr', root_path %>
    <br><br>
    Responsable de la publication : <%= link_to 'Christophe JULLIEN', magnetiseur_marseille_path %>
   </p>

  <h2>Mentions légales</h2>
    <p class="myP">Vous disposez d'un droit d'accès, de modification, de rectification et de suppression des données
    qui vous concernent (art. 34 de la loi "Informatique et Libertés" du 6 janvier 1978). </p>

  <h2>Droits d'auteur</h2>
    <p class="myP">Les vidéos, photos, textes et logos contenus sur le site web de
    <%= link_to 'www.soins-magnetiseur-marseille.fr', root_path %> sont protégés par des droits
    de propriété intellectuelle détenus par <%= link_to 'Christophe JULLIEN', magnetiseur_marseille_path %> et ses ayants droits.
    Les logiciels et applicatifs sont protégées par des droits de propriété intellectuelle détenus par des tiers.

    Leur utilisation est soumise à autorisation et exclusivement réservé à un usage de communication et publicité concernant
    soin-magnétiseur-marseille, sa marque, ses services et ses produits.
<br><br>
    Toute autre utilisation, transmission, rediffusion ou reproduction de ces photos, textes, logos et applications pour un objet autre
    que celui décrit auparavant, y compris sur un autre site web sans un accord écrit, express et préalable de soin-magnétiseur-marseille est
    strictement prohibée.

    Toute reproduction (transfert sur un autre support) ou utilisation de données du site web
    <%= link_to 'www.soins-magnetiseur-marseille.fr', root_path %>
    est exclusivement limitée à l'usage personnel et privé des utilisateurs du réseau internet, à l'exclusion de toute diffusion
    notamment à usage commercial.
<br><br>
    Toute reproduction ou utilisation, même à des fins privées, de la totalité ou d'une partie substantielle des données du site web
    <%= link_to 'www.soins-magnetiseur-marseille.fr', root_path %> est strictement interdite et susceptible de poursuites conformément
    aux articles L 343-1 et suivant du Code de la Propriété Intellectuelle, aux règlements nationaux et aux conventions internationales en vigueur.

    La violation de ces dispositions impératives soumet le contrevenant, et toutes les personnes responsables, aux peines pénales et
    civiles prévues par la Loi.</p>

  <h2>Information relative aux cookies</h2>
    <p class="myP">
    Ce site n'exploite pas les cookies.
    Néanmoins, certaines parties du site pourraient installer un « cookie » sur votre ordinateur. Un cookie ne nous permet pas de vous identifier.
    De manière générale, il enregistre des informations relatives à la navigation de votre ordinateur sur notre site
    (les pages que vous avez consultées, la date et l'heure de la consultation, etc..) que nous pourrions lire lors de vos visites ultérieures.
    <br>Ainsi, vous n'aurez peut-être pas besoin de remplir à nouveau certains formulaires ou nous pourrons mieux orienter votre navigation.
    La durée de conservation de ces informations dans votre ordinateur est variable et peut aller jusqu'à un an.

    Vous avez la possibilité de paramétrer votre navigateur pour vous opposer à l'enregistrement de « <%= link_to 'cookies', cookies_path %> »</p>
</div>

app/views/pages/soins.html.erb
<section class="soins"></section>

<div class="soinpresta">
<h1>Les soins énergétiques</h1>
<div class="bienfaits">
<h2>Ses bienfaits</h2>
  <p>Voici les différents systèmes du corps Humain avec leurs troubles correspondants. <br> Le travail énergétique permet d'agir sur ces
  différents systèmes en leur apportant plusieurs corrections énergétiques et dynamismes, sur plusieurs plans. <br> Cette liste met en lumière les champs
  d'actions de l'osthéofluidique</p>
              <div class="li">
              <ul class="myP">
                <li>Système orthopédique et locomoteur : entorses, tendinites, lombalgies, dorsalgies, cervicalgies, douleurs articulaires,
                scoliose, pubalgies, douleurs maxillaires</li>
                <li>Système ORL et pulmonaire : rhinites, sinusites, vertiges, bourdonnements, céphalées, migraines, bronchites, asthme</li>
                <li>Système digestif : Ballonnements, hernie hiatale, troubles hépato-biliaires, colites, constipation, gastrites,
                reflux gastro-oesophagiens </li>
                <li>Système neuro-végétatif : Etat dépressif, hypernervosité, anxiété, stress, troubles du sommeil</li>
                <li>Système neurologique : Névralgie cervico-brachiales, intercostales, fasciales, d'Arnold, sciatique</li>
                <li>Système cardio-vasculaire : Troubles circulatoire des membres inférieurs, hémorroïdes, palpitations oppressions</li>
              </ul>
            </div>
      <p>Informations importantes :</p>
      <p>
        Je ne suis pas médecin et ne formule aucun diagnostic. Les soins énergétiques, les massages de bien-être et de confort sont
        complémentaires de la médecine conventionnelle et ne doivent pas s’y substituer. En aucun cas vous ne devez interrompre un
        traitement médical sans en avoir eu l’accord de votre médecin. <br>
        Les soins énergétiques et les massages de bien-être et de confort sont confidentiels et l’anonymat du consultant est garanti. <br>
        Je vous recommande de bien lire ma page <%= link_to 'déontologie', deontologie_path, target: "_blank" %> avant
        de prendre rendez-vous.
      </p>
</div>
  <div class="soincard">
    <%# <div class="imgtxt" id="imgcab"></div> %>

    <img id="imgcab" src="/assets/encabinet2.png" alt="">

    <div id="txtcab" class="imgtxt">
      <h2>En Cabinet</h2>
      <p>
        Je vous recevrez dans mon cabinet, un lieu sain tant énergétiquement que propre.
        Vous n'avez pas besoin de vous dévétir, puiqu'il n'y a pas de manipultion ou de palpation.
        Seules les chaussures seront à enlever, d'une part pour faire le travail énergétique et d'autre part pour votre confort.
        <p>Les bracelets et colliers seront aussi à retirer, ils coupent la circulation énergétique.</p>
      </p>
      <br>
    </div>
  </div>

  <div class="soincard">
    <%# <div class="imgtxt" id="imgdist"></div> %>
    <img id="imgdist" src="/assets/soin distance.png" alt="">

    <dir id="txtdist" class="imgtxt">
      <h2>À distance</h2>
      <p>
        Le soin se passe comme en cabinet, à la différence que vous êtes chez vous.
        Je vous invite toutefois à vous mettre en tenue confortable et de vous installer
        dans une pièce isolée de tout dérangement. Les chaussures seront à enlever, d'une part pour faire
        le travail énergétique et d'autre part pour votre confort.
      <p>Les bracelets et colliers seront aussi à retirer, ils coupent la circulation énergétique.</p>

      <br>

    </dir>
  </div>

  <div class="soincard">
    <%# <div class="imgtxt" id="imglieu"></div> %>
    <img id="imglieu" src="/assets/encabinet6.png" alt="">

    <div id="txtlieu" class="imgtxt">
      <h2>Nettoyage des lieux</h2>
      <p>
        Tout comme les soins de magnétisme ou d'énergétique, le nettoyage des lieux est aussi un soin de votre environnement.
        En effet, durant la nuit, d'une part, on libère des émotions et certaines énergies mortes pendant le sommeil.
        D'autre part, on libère aussi des émotions en journée, quand on est présent. Le lieu se charge est devient désagréable à vivre,
        au fil du temps.
      </p>
      <br>
      <p>Note :</p>
      <p>
        Le nettoyage des lieux ne remplace pas une étude Feng Shui ou de géobiologie, qui corrige sur le long terme les dysfonctionnements
        énergétiques. Toutefois, ce type de soin des lieux reste très efficace ponctuellement.
     </p>

    </div>
  </div>

 <h1>Massage Intuitif Énergétique</h1>
  <div class="soincard">
    <%# <div class="imgtxt" id="imglieu"></div> %>
    <img id="imglieu" src="/assets/encabinet6.png" alt="">

    <div id="txtlieu" class="imgtxt">
      <h2>Massage bien-être</h2>
      <p>
        Massage bien-être et de confort en intuitif, il relance les énergies et dénoue certains noeux énergétiques. <br>
        Il apporte détente, relaxation et aide à réduire le stress ou l'anxiété ; il redonne force et vigueur. <br>
        Idéal pour lâcher prise et fait naître une nouvelle conscience corporelle<br>
        Il peut aider à une reprise du tonus musculaire et peut réduire les courbatures. <br>
        Favorisant un bien-être général, il améliore la qualité du sommeil et apaide le système nerveux, . <br>
        Des mouvements fluides et enveloppants s'alternent par pressions légères ou profondes, énergisantes, avec une huile de noyaux
        d'abricots de qualité.
      </p>

      <br>
      <p>Informations importantes :</p>
      <p>Vérifiez votre allergie à l'huile de noyaux d'abricots avant de choisir ce type de soin. Aucune huile essentielle n'y est ajoutée.</p>
    </div>
  </div>

<h1>Guidance Spirituelle</h1>
  <div class="soincard">
    <%# <div class="imgtxt" id="imggs"></div> %>
    <img id="imggs" src="/assets/meditation.gif" alt="">

    <dir id="txtgs" class="imgtxt">
      <h2>Guidance Spirituelle</h2>
      <p>
        La Guidance Spirituelle est là pour vous aidez à trouver des réponses là où vous n'avez pas réussi à en trouver.
        Elle peut se faire seule ou en couple.
        Grâce à mes ressentis, je vous apporterai un axe de réflexion pour que vous trouviez votre solution
        à la difficulté que vous traversez.
        C'est donc un accompagnement vers vous-même qui vous est proposé.
      </p>
      <br>
      <p>Informations importantes :</p>
      <p>Il ne s'agit pas de séance de psychothérapies. Seul le psychiatre, le psychothérapeute ou le psychologue peuvent le faire !</p>
    </dir>
  </div>

</div>

app/views/pages/vosquestions.html.erb
<section class="questions"></section>

<div class="vosquestions">
  <h2>Combien de temps dure un soin ?</h2>
  <div class="cache">
    <p>Un soin dure généralement 1h ; il peut-être plus long ou plus légèrement plus court selon le travail qui est en train de se poser et
    aussi selon ce que vous pourrez lâcher.
    </p>
  </div>
  <br>

  <h2>Combien de séance faut-il ?</h2>
  <div class="cache">
   <p>La réponse n’est pas aussi directe. Les traumatismes récents et relativement légers peuvent se régler en une séance,
      mais ceux qui sont plus anciens et plus lourds nécessitent très souvent plusieurs séances, posées en accord avec le vous dès la prise
      de rendez-vous.</p>
    <p>
      En effet, <%# comme indiquée dans ma <%= link_to 'déontologie', deontologie_path, target: "_blank" %> vous êtes aussi responsable de sa
      participation au soin et de votre capacité à vouloir lâcher ce qui vous pèse.
      Je ne peux pas et je ne prends pas le droit d’aller au-delà de ce qui sera possible de faire, au-delà de votre limite.
    </p>
    </div>
   <br>

  <h2>Qui peut recevoir un soin ?</h2>
  <div class="cache">
    <p>Toute personne majeure ou mineure peut recevoir un soin, il n’y a pas de condition préalable.</p>
    </div>
  <br>

  <h2>Puis-je prendre rendez-vous pour une personne autre que moi ?</h2>
  <div class="cache">
    <p>Non.</p>
    <p>
      Seule la patiente, le patient, prend rendez-vous pour elle-même, lui-même, sauf le parent ou le représentant légal pour l'enfant
      encore mineur.
    </p>
    </div>
  <br>

  <h2>Comment puis-je savoir si mon habitat est énergétiquement lourd ou à nettoyer ?</h2>
  <div class="cache">
    <p>Généralement, on a des indicateurs qui nous renseignents :</p>
      <p>- quand on revient de promenade (notamment en forêt), on pourrait ressentir l’habitat comme pesant ou quelque
          chose d’autre de désagréable (fatigue soudaine, mal de crâne, etc...)</p>
      <p>- On pourrait aussi sentir que quelque chose ne va pas dans une pièce ou une autre</p>
      <p>- Si l’on éprouve le besoin de changer régulièrement les meubles de place, ou de brûler de l’encens,
     ou d’aérer souvent et longtemps… peuvent être aussi des indicateurs</p>
     <p>Si vous savez le faire, tester vos pièces énergétiquement au pendule ou avec tout autre outil que vous connaissez efficace.</p>
     </div>
  <br>

  <h2>Dois-je arrêter mon traitement médical ?</h2>
  <div class="cache">
  <p>Je ne suis pas en mesure, ni en autorité de vous dire de continuer ou d'arrêter votre traitement, ni de vous conseiller sur votre
  traitement actuel.</p>
  <p>Seul votre médecin est en capacité de le faire !</p>
  </div>
  <br>

</div>

app/views/temoignages/index.html.erb
<section class="temoignage"></section>

<div class="tmg">
  <h1>Partagez-nous votre expérience avec Christophe</h1>
  <div id="bouton">
    <h2>Partagez votre expérience</h2>
  </div>
  <br>
  <hr>
    <% @temoignages.each do |t| %>
    <p class="myP">
      <%= t.prenom.capitalize %>, <%= t.nom.capitalize.first %>.
      <br>
      <br>
      <%= t.commentaires %>
    </p>
    <hr>
    <% end %>
</div>